### ISSUE TITLE
 Issues with routing succes/cancel/callback.

### ISSUE THREAD

**Issue by Fredrik-H-Laastad** [DIBS-Payment-Services/Opencart#3]
Opencart: 2.0.2.0 
Vqmod: 2.5.1
DIBS module: dibsfw vqmod 3.0.3 

Default OpenCart setup, the only custom extension is DIBS

There seems to be an issue when returning from the payment-window, as it isn't re-routing from /payment/dibsfw/success and I recieve a 404 error.

Manually changing url to /index.php?route=/payment/dibsfw/success/*values* redirects to /checkout/success

I have included the code from the vqcached "~Controller_Common_Seo_Url.php" and the .htacces file

Can you please see if anything is out of the ordinary?

## .htaccess
```
# 1.To use URL Alias you need to be running apache with mod_rewrite enabled. 

# 2. In your opencart directory rename htaccess.txt to .htaccess.

# For any support issues please visit: http://www.opencart.com

Options +FollowSymlinks

# Prevent Directoy listing 
Options -Indexes

# Prevent Direct Access to files
<FilesMatch "(?i)((\.tpl|\.ini|\.log|(?<!robots)\.txt))">
 Order deny,allow
 Deny from all
</FilesMatch>

# SEO URL Settings
RewriteEngine On
# If your opencart installation does not run on the main web folder make sure you folder it does run in ie. / becomes /shop/ 

RewriteBase /caspar/OpenCart2/
RewriteRule ^sitemap.xml$ index.php?route=feed/google_sitemap [L]
RewriteRule ^googlebase.xml$ index.php?route=feed/google_base [L]
RewriteRule ^system/download/(.*) /index.php?route=error/not_found [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !.*\.(ico|gif|jpg|jpeg|png|js|css)
RewriteRule ^([^?]*) index.php?_route_=$1 [L,QSA]

### Additional Settings that may need to be enabled for some servers 
### Uncomment the commands by removing the # sign in front of it.
### If you get an "Internal Server Error 500" after enabling any of the following settings, restore the # as this means your host doesn't allow that.

# 1. If your cart only allows you to add one item at a time, it is possible register_globals is on. This may work to disable it:
# php_flag register_globals off

# 2. If your cart has magic quotes enabled, This may work to disable it:
# php_flag magic_quotes_gpc Off

# 3. Set max upload file size. Most hosts will limit this and not allow it to be overridden but you can try
# php_value upload_max_filesize 999M

# 4. set max post size. uncomment this line if you have a lot of product options or are getting errors where forms are not saving all fields
# php_value post_max_size 999M

# 5. set max time script can take. uncomment this line if you have a lot of product options or are getting errors where forms are not saving all fields
# php_value max_execution_time 200

# 6. set max time for input to be recieved. Uncomment this line if you have a lot of product options or are getting errors where forms are not saving all fields
# php_value max_input_time 200

# 7. disable open_basedir limitations
# php_admin_value open_basedir none

```

## Controller_Common_Seo_Url.php
```
<?php
class ControllerCommonSeoUrl extends Controller {
	public function index() {
		// Add rewrite to url class
		if ($this->config->get('config_seo_url')) {
			$this->url->addRewrite($this);
		}

		// Decode URL
		if (isset($this->request->get['_route_'])) {
			$parts = explode('/', $this->request->get['_route_']);

			// remove any empty arrays from trailing
			if (utf8_strlen(end($parts)) == 0) {
				array_pop($parts);
			}

			foreach ($parts as $part) {
				$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "url_alias WHERE keyword = '" . $this->db->escape($part) . "'");

				if ($query->num_rows) {
					$url = explode('=', $query->row['query']);

					if ($url[0] == 'product_id') {
						$this->request->get['product_id'] = $url[1];
					}

					if ($url[0] == 'category_id') {
						if (!isset($this->request->get['path'])) {
							$this->request->get['path'] = $url[1];
						} else {
							$this->request->get['path'] .= '_' . $url[1];
						}
					}

					if ($url[0] == 'manufacturer_id') {
						$this->request->get['manufacturer_id'] = $url[1];
					}

					if ($url[0] == 'information_id') {
						$this->request->get['information_id'] = $url[1];
					}

					if ($query->row['query'] && $url[0] != 'information_id' && $url[0] != 'manufacturer_id' && $url[0] != 'category_id' && $url[0] != 'product_id') {
						$this->request->get['route'] = $query->row['query'];
					}
				} else {
					$this->request->get['route'] = 'error/not_found';

					break;
				}
			}

			if (!isset($this->request->get['route'])) {
				if (isset($this->request->get['product_id'])) {
					$this->request->get['route'] = 'product/product';
				} elseif (isset($this->request->get['path'])) {
					$this->request->get['route'] = 'product/category';
				} elseif (isset($this->request->get['manufacturer_id'])) {
					$this->request->get['route'] = 'product/manufacturer/info';
				} elseif (isset($this->request->get['information_id'])) {
					$this->request->get['route'] = 'information/information';
				}

                         if(preg_match("/^payment\/dibsfw\/(success|cancel|callback)\/?$/", $this->request->get['_route_'], $match)) {
                            $this->request->get['route'] = 'payment/dibsfw/' . $match[1];}

			}

			if (isset($this->request->get['route'])) {
				return new Action($this->request->get['route']);
			}
		}
	}

	public function rewrite($link) {
		$url_info = parse_url(str_replace('&amp;', '&', $link));

		$url = '';

		$data = array();

		parse_str($url_info['query'], $data);

		foreach ($data as $key => $value) {
			if (isset($data['route'])) {
				if (($data['route'] == 'product/product' && $key == 'product_id') || (($data['route'] == 'product/manufacturer/info' || $data['route'] == 'product/product') && $key == 'manufacturer_id') || ($data['route'] == 'information/information' && $key == 'information_id')) {
					$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "url_alias WHERE `query` = '" . $this->db->escape($key . '=' . (int)$value) . "'");

					if ($query->num_rows && $query->row['keyword']) {
						$url .= '/' . $query->row['keyword'];

						unset($data[$key]);
					}
				} elseif ($key == 'path') {
					$categories = explode('_', $value);

					foreach ($categories as $category) {
						$query = $this->db->query("SELECT * FROM " . DB_PREFIX . "url_alias WHERE `query` = 'category_id=" . (int)$category . "'");

						if ($query->num_rows && $query->row['keyword']) {
							$url .= '/' . $query->row['keyword'];
						} else {
							$url = '';

							break;
						}
					}

					unset($data[$key]);
				}
			}
		}

		if ($url) {
			unset($data['route']);

			$query = '';

			if ($data) {
				foreach ($data as $key => $value) {
					$query .= '&' . rawurlencode((string)$key) . '=' . rawurlencode((string)$value);
				}

				if ($query) {
					$query = '?' . str_replace('&', '&amp;', trim($query, '&'));
				}
			}

			return $url_info['scheme'] . '://' . $url_info['host'] . (isset($url_info['port']) ? ':' . $url_info['port'] : '') . str_replace('/index.php', '', $url_info['path']) . $url . $query;
		} else {
			return $link;
		}
	}
}
```

**Comment by maxwhite** [comment]
It seems you didn't enable seo urls in Opencart admin, you Opencart must work with clean urls /payment/dibsfw/success

**Comment by Fredrik-H-Laastad** [comment]
SEO URLS are turned on

![screenshot_2015-05-13-16-48-43](https://cloud.githubusercontent.com/assets/8394150/7613281/15a75da2-f990-11e4-8f40-58377ff7a80a.png)

**Comment by maxwhite** [comment]
ok, and another clean urls works ? like categories or products ?

**Comment by Fredrik-H-Laastad** [comment]
Hi, 

Yes links like: "/desktops/mac/imac" work as intended.

**Comment by maxwhite** [comment]
Try to modify /catalog/common/seo_url.php 
and add this 
 if(preg_match("/^payment\/dibsfw\/(success|cancel|callback)\/?$/", $this->request->get['_route_'], $match)) {
                            $this->request->get['route'] = 'payment/dibsfw/' . $match[1];}
like in vqmod file Controller_Common_Seo_Url.php

Maybe it is problem with vqmod ?

and try this url:  payment/dibsfw/success

**Comment by Fredrik-H-Laastad** [comment]
Done, also deleted the dibs xml and updated vqmod & cache.

Still recieving the same error.

**Comment by Sportmasters** [comment]
Hey.
I also have the same problem, Any solution?
I use v1564.
Payment says success!!
but when you press for a receive you get error 404.
http://www.mysite.se/payment/dibsfw/success

You get email that order is made and it is in admin interface as a new payment.
Customer dont get receive and i dont get order in opencart/sale.
Please help.

**Comment by maxwhite** [comment]
Hi,
try to change in file
vqmod\xml\dibsfw_urls.xml
<search position="after" offset="1">
to
<search position="after" offset="3">

**Comment by Sportmasters** [comment]
Hey
www.sporttotal.se/payment/dibsfw/callback
Sorry...I still dont have any page for that...Should i uninstall and install all again? Does it help
Best Regards Conny

Date: Mon, 15 Jun 2015 05:57:32 -0700

**Comment by Sportmasters** [comment]
Hey again
In language file there is no "text_title" so where to add Dibs payment in checkout so customer see it?It is okey to do as many test buys you like just tell me and I delete them.
Best Regards Conny

Date: Mon, 15 Jun 2015 05:57:32 -0700

**Comment by Sportmasters** [comment]
Hey again
Attached are my admin settings....Forgot to send it earlier...
Best Regards Conny

Date: Mon, 15 Jun 2015 05:57:32 -0700

**Comment by Fredrik-H-Laastad** [comment]
Hi,

Changing to offset 3 successfully triggered the rerouting on the client return, but callbacks are receiving a HTTP 503 error, so the orders aren't registered in the shop.

I'm suspecting this might be a .htaccess issue, but do you have any insight to share? 

```
HTTP error status code from transaction:	503

HTTP error reply from transaction:	

<!DOCTYPE html>
<!--[if IE]><![endif]-->
<!--[if IE 8 ]><html dir="ltr" lang="en" class="ie8"><![endif]-->
<!--[if IE 9 ]><html dir="ltr" lang="en" class="ie9"><![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html dir="ltr" lang="en">
<!--<![endif]-->
<head>
```

**Comment by Fredrik-H-Laastad** [comment]
Scrap that last part, forgot to put OpenCart out of maintenance mode...

Works perfectly now! Thank you :+1:

**Comment by Sportmasters** [comment]
Incredible worse support.
I tried all and still not working.
I bought the Qhorias Flexwin and worked after 1 min.
It cost me 70USD so to all having problems, buy his module!
